version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    networks:
      - postgres
    environment:
      - POSTGRES_USER=shoe_dba
      - POSTGRES_PASSWORD=shoe1234
      - POSTGRES_DB=shoe_db
    expose:
      - 5432
    ports:
      - "5432:5432"

  pgadmin4:
    image: dpage/pgadmin4
    networks:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shoe-service.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5433:80
    depends_on:
      - postgres

  redis:
    image: "redis:alpine"
    container_name: "redis"
    networks:
      - postgres
    expose:
      - 6379
    ports:
      - "6379:6379"

  spring-boot-admin-server:
    image: "waggins/spring-boot-admin-server:v1"
    networks:
      - postgres
    ports:
      - "8091:8091"
    restart: unless-stopped

  authorization-server:
    image: "waggins/authorization-server:v1"
    networks:
      - postgres
    ports:
      - "8090:8090"
    restart: unless-stopped

  shoe-service:
    image: "waggins/shoe-service:v4"
    networks:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    links:
      - postgres
      - spring-boot-admin-server
      - authorization-server
      - redis
    depends_on:
      - postgres
      - spring-boot-admin-server
      - authorization-server
      - redis

  shoe-ui:
    image: "waggins/shoe-ui:v4"
    networks:
      - postgres
    ports:
      - "3000:3000"
    restart: unless-stopped
    links:
      - shoe-service
    depends_on:
      - shoe-service

networks:
  postgres:
    driver: bridge

